[package]
name = "file_encryptor_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-colorizer = "1"
regex = "1"
aes = "0.8.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
